version: '3.5'

x-environment: &common-environment
  POSTGRES_DB: postgres
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  REDIS_URL: "redis://redis:6379/0"

services:
  appserver:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment:
      <<: *common-environment
      PORT: 8000
      HOST: 0.0.0.0
      DJANGO_DEBUG: "True"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
      - celery
      - redis
    command: /start.sh

  db:
    image: postgres
    environment:
      <<: *common-environment

  redis:
    image: "redis:alpine"
    ports:
      - "63798:6379"

  celery:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    environment: *common-environment
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    command: celery -A config worker -l info
